### ISSUE TITLE
In Heb calendar how can I get the next year ?

### ISSUE THREAD

**Issue by joseph-vedadi** [simlist/pyluach#22] opened 2022-06-30 18:31 UTC
For Birthday or Yahrtzeit, How can I calculate the next year?
Let's assume the date is 5- Adar 2, when will it be next year?

**Comment by simlist** [comment] 2022-07-26 04:30
Duplicate of https://github.com/simlist/pyluach/issues/23.

**Closed by simlist** 2022-07-26 04:30 UTC
